### ISSUE TITLE
Text files missing in output folder

### ISSUE THREAD

**Issue by D4ftchunk** [rakuri255/UltraSinger#118]
ive installed and reinstalled your **amazing** program but every convert i do make i get all the file except the TEXT file.

ive put the full log below (ignore the top part i made a BATCH file that i can simply use to copy and paste into.

Thank you for your hard work its a great program hope you can help

![files](https://github.com/rakuri255/UltraSinger/assets/156721334/a2fbca6f-3221-41d2-8157-a7ff092cb775)

C:\Users\ridle\Desktop\UltraSinger-main>set /p vidurl=GO ON Shove Your Tube Link Here:
GO ON Shove Your Tube Link Here:https://www.youtube.com/watch?v=bE3Kvqyef_E

C:\Users\ridle\Desktop\UltraSinger-main>c:

C:\Users\ridle\Desktop\UltraSinger-main>cd\

C:\>cd Users\ridle\Desktop\UltraSinger-main

C:\Users\ridle\Desktop\UltraSinger-main>call .venv\Scripts\activate
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.

[UltraSinger] *****************************
[UltraSinger] UltraSinger Version: 0.0.8
[UltraSinger] *****************************
[UltraSinger] Checking GPU support for tensorflow and pytorch.
[UltraSinger] tensorflow - using cuda gpu.
[UltraSinger] pytorch - using cuda gpu.
[UltraSinger] full automatic mode
[youtube] Extracting URL: https://www.youtube.com/watch?v=bE3Kvqyef_E
[youtube] bE3Kvqyef_E: Downloading webpage
[youtube] bE3Kvqyef_E: Downloading ios player API JSON
[youtube] bE3Kvqyef_E: Downloading android player API JSON
[youtube] bE3Kvqyef_E: Downloading m3u8 information
[UltraSinger] Searching song in musicbrainz
[UltraSinger] Found Titel and Artist Disconnect by Becky Hill & Chase & Status
[UltraSinger] Found release year: 2023-07-14
[UltraSinger] Creating output folder. -> C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect
[UltraSinger] Downloading Audio
[youtube] Extracting URL: https://www.youtube.com/watch?v=bE3Kvqyef_E
[youtube] bE3Kvqyef_E: Downloading webpage
[youtube] bE3Kvqyef_E: Downloading ios player API JSON
[youtube] bE3Kvqyef_E: Downloading android player API JSON
[youtube] bE3Kvqyef_E: Downloading m3u8 information
[info] bE3Kvqyef_E: Downloading 1 format(s): 251
[download] Destination: C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect\Becky Hill & Chase & Status - Disconnect
[download] 100% of    2.39MiB in 00:00:00 at 24.87MiB/s
[ExtractAudio] Destination: C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect\Becky Hill & Chase & Status - Disconnect.mp3
Deleting original file C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect\Becky Hill & Chase & Status - Disconnect (pass -k to keep)
[UltraSinger] Downloading Video
[youtube] Extracting URL: https://www.youtube.com/watch?v=bE3Kvqyef_E
[youtube] bE3Kvqyef_E: Downloading webpage
[youtube] bE3Kvqyef_E: Downloading ios player API JSON
[youtube] bE3Kvqyef_E: Downloading android player API JSON
[youtube] bE3Kvqyef_E: Downloading m3u8 information
[info] bE3Kvqyef_E: Downloading 1 format(s): 625+140
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 34
[download] Destination: C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect\Becky Hill & Chase & Status - Disconnect.f625.mp4
[download] 100% of  333.21MiB in 00:00:08 at 38.28MiB/s
[download] Destination: C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect\Becky Hill & Chase & Status - Disconnect.f140.m4a
[download] 100% of    2.47MiB in 00:00:00 at 28.43MiB/s
[Merger] Merging formats into "C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect\Becky Hill & Chase & Status - Disconnect.mp4"
Deleting original file C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect\Becky Hill & Chase & Status - Disconnect.f625.mp4 (pass -k to keep)
Deleting original file C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect\Becky Hill & Chase & Status - Disconnect.f140.m4a (pass -k to keep)
[UltraSinger] Downloading thumbnail
[youtube] Extracting URL: https://www.youtube.com/watch?v=bE3Kvqyef_E
[youtube] bE3Kvqyef_E: Downloading webpage
[youtube] bE3Kvqyef_E: Downloading ios player API JSON
[youtube] bE3Kvqyef_E: Downloading android player API JSON
[youtube] bE3Kvqyef_E: Downloading m3u8 information
[UltraSinger] Creating output folder. -> C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect\cache
[UltraSinger] Separating vocals from audio with demucs and cuda as worker.
Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in C:\Users\ridle\Desktop\UltraSinger-main\src\separated\htdemucs
Separating track C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect\Becky Hill & Chase & Status - Disconnect.mp3
100%|██████████████████████████████████████████████| 163.79999999999998/163.79999999999998 [00:06<00:00, 26.02seconds/s]
[UltraSinger] Converting wav to mp3
[UltraSinger] Reduce noise from vocal audio with ffmpeg.
[UltraSinger] Converting audio for AI
[UltraSinger] Mute audio parts with no singing
[UltraSinger] Loading whisper with model large-v2 and cuda as worker
Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
[UltraSinger] Your GPU does not support efficient float16 computation; run UltraSinger with '--whisper_compute_type int8'
Export Complete
Press any key to continue . . .

**Comment by rakuri255** [comment]
Your problem is that you have an old gpu. As the last UltraSinger comment says `[UltraSinger] Your GPU does not support efficient float16 computation; run UltraSinger with '--whisper_compute_type int8'
Export Complete`

Please try it again with  '--whisper_compute_type int8'

**Comment by D4ftchunk** [comment]
thank you! 

Where do i pout that or activate that whipser please?

**Comment by rakuri255** [comment]
`- i https://www.youtube.com/watch?v=bE3Kvqyef_E --whisper_compute_type int8`

**Comment by D4ftchunk** [comment]
[UltraSinger] *****************************
[UltraSinger] UltraSinger Version: 0.0.8
[UltraSinger] *****************************
[UltraSinger] Checking GPU support for tensorflow and pytorch.
[UltraSinger] tensorflow - using cuda gpu.
[UltraSinger] pytorch - using cuda gpu.
[UltraSinger] full automatic mode
[UltraSinger] Searching song in musicbrainz
[UltraSinger] Found Titel and Artist I by Various Artists
[UltraSinger] Found release year: 2017-04-13
[UltraSinger] Creating output folder. -> output\Various Artists - I
Traceback (most recent call last):
  File "C:\Users\ridle\Desktop\UltraSinger-main\src\ultrasinger.py", line 984, in <module>
    main(sys.argv[1:])
  File "C:\Users\ridle\Desktop\UltraSinger-main\src\ultrasinger.py", line 883, in main
    run()
  File "C:\Users\ridle\Desktop\UltraSinger-main\src\ultrasinger.py", line 336, in run
    ) = infos_from_audio_input_file()
  File "C:\Users\ridle\Desktop\UltraSinger-main\src\ultrasinger.py", line 728, in infos_from_audio_input_file
    os_helper.copy(settings.input_file_path, song_output)
  File "C:\Users\ridle\Desktop\UltraSinger-main\src\modules\os_helper.py", line 24, in copy
    shutil.copy(original, target)
  File "C:\Python310\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '-i'
Export Complete
Press any key to continue . . .

**Comment by rakuri255** [comment]
please show the full log. With the comand line you typed in

**Comment by D4ftchunk** [comment]
i didnt put py ultrasinger.py at front its running now! ill let you know

**Comment by D4ftchunk** [comment]
PROBLEM SOLVED! thank you...i do have 1080ti ??  here is the log

Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

C:\Users\ridle\Desktop\UltraSinger-main>.venv\Scripts\activate

(.venv) C:\Users\ridle\Desktop\UltraSinger-main>cd src

(.venv) C:\Users\ridle\Desktop\UltraSinger-main\src>py UltraSinger.py
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.

[UltraSinger] *****************************
[UltraSinger] UltraSinger Version: 0.0.8
[UltraSinger] *****************************

    UltraSinger.py [opt] [mode] [transcription] [pitcher] [extra]

    [opt]
    -h      This help text.
    -i      Ultrastar.txt
            audio like .mp3, .wav, youtube link
    -o      Output folder

    [mode]
    ## INPUT is audio ##
    default  Creates all

    # Single file creation selection is in progress, you currently getting all!
    (-u      Create ultrastar txt file) # In Progress
    (-m      Create midi file) # In Progress
    (-s      Create sheet file) # In Progress

    ## INPUT is ultrastar.txt ##
    default  Creates all

    # Single selection is in progress, you currently getting all!
    (-r      repitch Ultrastar.txt (input has to be audio)) # In Progress
    (-p      Check pitch of Ultrastar.txt input) # In Progress
    (-m      Create midi file) # In Progress

    [transcription]
    # Default is whisper
    --whisper               Multilingual model > tiny|base|small|medium|large-v1|large-v2  >> ((default) is large-v2
                            English-only model > tiny.en|base.en|small.en|medium.en
    --whisper_align_model   Use other languages model for Whisper provided from huggingface.co
    --language              Override the language detected by whisper, does not affect transcription but steps after transcription
    --whisper_batch_size    Reduce if low on GPU mem >> ((default) is 16)
    --whisper_compute_type  Change to "int8" if low on GPU mem (may reduce accuracy) >> ((default) is "float16" for cuda devices, "int8" for cpu)

    [pitcher]
    # Default is crepe
    --crepe            tiny|full >> ((default) is full)
    --crepe_step_size  unit is miliseconds >> ((default) is 10)

    [extra]
    --hyphenation           True|False >> ((default) is True)
    --disable_separation    True|False >> ((default) is False)
    --disable_karaoke       True|False >> ((default) is False)
    --create_audio_chunks   True|False >> ((default) is False)
    --plot                  True|False >> ((default) is False)
    --format_version        0.3.0|1.0.0|1.1.0 >> ((default) is 1.0.0)

    [device]
    --force_cpu             True|False >> ((default) is False)  All steps will be forced to cpu
    --force_whisper_cpu     True|False >> ((default) is False)  Only whisper will be forced to cpu
    --force_crepe_cpu       True|False >> ((default) is False)  Only crepe will be forced to cpu


(.venv) C:\Users\ridle\Desktop\UltraSinger-main\src>
(.venv) C:\Users\ridle\Desktop\UltraSinger-main\src>py ultrasinger.py -i https://www.youtube.com/watch?v=bE3Kvqyef_E --whisper_compute_type int8
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.

[UltraSinger] *****************************
[UltraSinger] UltraSinger Version: 0.0.8
[UltraSinger] *****************************
[UltraSinger] Checking GPU support for tensorflow and pytorch.
[UltraSinger] tensorflow - using cuda gpu.
[UltraSinger] pytorch - using cuda gpu.
[UltraSinger] full automatic mode
[youtube] Extracting URL: https://www.youtube.com/watch?v=bE3Kvqyef_E
[youtube] bE3Kvqyef_E: Downloading webpage
[youtube] bE3Kvqyef_E: Downloading ios player API JSON
[youtube] bE3Kvqyef_E: Downloading android player API JSON
[youtube] bE3Kvqyef_E: Downloading m3u8 information
[UltraSinger] Searching song in musicbrainz
[UltraSinger] Found Titel and Artist Disconnect by Becky Hill & Chase & Status
[UltraSinger] Found release year: 2023-07-14
[UltraSinger] Creating output folder. -> C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)
[UltraSinger] Downloading Audio
[youtube] Extracting URL: https://www.youtube.com/watch?v=bE3Kvqyef_E
[youtube] bE3Kvqyef_E: Downloading webpage
[youtube] bE3Kvqyef_E: Downloading ios player API JSON
[youtube] bE3Kvqyef_E: Downloading android player API JSON
[youtube] bE3Kvqyef_E: Downloading m3u8 information
[info] bE3Kvqyef_E: Downloading 1 format(s): 251
[download] Destination: C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\Becky Hill & Chase & Status - Disconnect
[download] 100% of    2.39MiB in 00:00:00 at 31.41MiB/s
[ExtractAudio] Destination: C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\Becky Hill & Chase & Status - Disconnect.mp3
Deleting original file C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\Becky Hill & Chase & Status - Disconnect (pass -k to keep)
[UltraSinger] Downloading Video
[youtube] Extracting URL: https://www.youtube.com/watch?v=bE3Kvqyef_E
[youtube] bE3Kvqyef_E: Downloading webpage
[youtube] bE3Kvqyef_E: Downloading ios player API JSON
[youtube] bE3Kvqyef_E: Downloading android player API JSON
[youtube] bE3Kvqyef_E: Downloading m3u8 information
[info] bE3Kvqyef_E: Downloading 1 format(s): 625+140
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 34
[download] Destination: C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\Becky Hill & Chase & Status - Disconnect.f625.mp4
[download] 100% of  333.21MiB in 00:00:07 at 43.79MiB/s
[download] Destination: C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\Becky Hill & Chase & Status - Disconnect.f140.m4a
[download] 100% of    2.47MiB in 00:00:00 at 22.09MiB/s
[Merger] Merging formats into "C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\Becky Hill & Chase & Status - Disconnect.mp4"
Deleting original file C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\Becky Hill & Chase & Status - Disconnect.f140.m4a (pass -k to keep)
Deleting original file C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\Becky Hill & Chase & Status - Disconnect.f625.mp4 (pass -k to keep)
[UltraSinger] Downloading thumbnail
[youtube] Extracting URL: https://www.youtube.com/watch?v=bE3Kvqyef_E
[youtube] bE3Kvqyef_E: Downloading webpage
[youtube] bE3Kvqyef_E: Downloading ios player API JSON
[youtube] bE3Kvqyef_E: Downloading android player API JSON
[youtube] bE3Kvqyef_E: Downloading m3u8 information
[UltraSinger] Creating output folder. -> C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\cache
[UltraSinger] Separating vocals from audio with demucs and cuda as worker.
Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in C:\Users\ridle\Desktop\UltraSinger-main\src\separated\htdemucs
Separating track C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\Becky Hill & Chase & Status - Disconnect.mp3
100%|██████████████████████████████████████████████| 163.79999999999998/163.79999999999998 [00:06<00:00, 26.98seconds/s]
[UltraSinger] Converting wav to mp3
[UltraSinger] Reduce noise from vocal audio with ffmpeg.
[UltraSinger] Converting audio for AI
[UltraSinger] Mute audio parts with no singing
[UltraSinger] Loading whisper with model large-v2 and cuda as worker
No language specified, language will be first be detected for each audio file (increases inference time).
100%|█████████████████████████████████████| 16.9M/16.9M [00:00<00:00, 79.5MiB/s]
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.1.3. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint C:\Users\ridle\.cache\torch\whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.1+cu117. Bad things might happen unless you revert torch to 1.x.
[UltraSinger] Transcribing C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\cache\Becky Hill & Chase & Status - Disconnect_mute.wav
Detected language: en (0.77) in first 30s of audio...
Downloading: "https://download.pytorch.org/torchaudio/models/wav2vec2_fairseq_base_ls960_asr_ls960.pth" to C:\Users\ridle/.cache\torch\hub\checkpoints\wav2vec2_fairseq_base_ls960_asr_ls960.pth
100%|███████████████████████████████████████████████████████████████████████████████| 360M/360M [00:03<00:00, 96.0MB/s]
[UltraSinger] Hyphenate using language code: en
[UltraSinger] Error in hyphenation for language  en, maybe you want to disable it?
[UltraSinger] Removing silent parts from transcription data
[UltraSinger] Pitching with crepe and model full and cuda as worker
2024-01-17 00:37:08.564250: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-17 00:37:09.229320: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8404 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1
2024-01-17 00:37:18.775162: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8500
501/501 [==============================] - 7s 12ms/step
[UltraSinger] Creating midi notes from pitched data
[UltraSinger] Creating Ultrastar notes from midi data
[UltraSinger] BPM is 117.19
[UltraSinger] Creating C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\Becky Hill & Chase & Status - Disconnect.txt from transcription.
[UltraSinger] Creating C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\Becky Hill & Chase & Status - Disconnect [Karaoke].txt from transcription.
[UltraSinger] Parse ultrastar txt -> C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\Becky Hill & Chase & Status - Disconnect.txt
[UltraSinger] Calculating Ultrastar Points
[UltraSinger] Simple (octave high ignored) points
[UltraSinger] Total: 6285, notes: 5728, line bonus: 557, golden notes: 0
[UltraSinger] Accurate (octave high matches) points:
[UltraSinger] Total: 6248, notes: 5699, line bonus: 549, golden notes: 0
[UltraSinger] Creating Midi with pretty_midi
[UltraSinger] Creating midi instrument from Ultrastar txt
[UltraSinger] Creating midi file -> C:\Users\ridle\Desktop\UltraSinger-main\src\output\Becky Hill & Chase & Status - Disconnect (1)\Becky Hill & Chase & Status - Disconnect.mid

[UltraSinger] Do you like UltraSinger? Want it to be even better? Then help with your support!
[UltraSinger] See project page -> https://github.com/rakuri255/UltraSinger
[UltraSinger] This will help a lot to keep this project alive and improved.

(.venv) C:\Users\ridle\Desktop\UltraSinger-main\src>

**Comment by rakuri255** [comment]
I close this issue since there is no issue on UltraSinger side ;D
Please go to https://discord.com/invite/7EqhhjFd if you need more help.
