### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by binarygeek119** [rakuri255/UltraSinger#119]
my desktop is a amp system but my unraid server is nvidia but i can only run a docker image for apps.

idealy i docker image would have a web ui.

the way i see it is docker setup pass the gpu to the image and a storage link
/temp:/serverside/temp 
/songs:/serverside/songs

the webui you can upload a mp3, ogg, wav, etc or paste a youtube link. this then pass it to the program to run. idealy see the progress in web ui.

then the final files are located in /songs which on the host side would be what ever you set it up as.
would be nice to be able top download a zip of the finshed files thought web ui.

i would recommended taking a look at metube docker web ui for ideas for the web ui part.
https://github.com/alexta69/metube

**Comment by binarygeek119** [comment]
subgen uses whisper to generate subtitles and its setup for docker. maybe this can be applied here.
https://github.com/McCloudS/subgen

**Comment by rakuri255** [comment]
Still need an CI
