### ISSUE TITLE
repitch not working (windows)

### ISSUE THREAD

**Issue by hanz-s** [rakuri255/UltraSinger#120]
hi,

i was trying to repitch, running the tool under windows with gitbash, and it did not work.
i could fix it with changing the line:

ultrastar_writer.py:173:
if line.startswith(f"#{UltrastarTxtNoteTypeTag.NORMAL} "):
to:
if line.startswith(UltrastarTxtNoteTypeTag.NORMAL):

Is it a bug or is it intented that there should be a "#:" at the start of the line instead of ":"?

**Comment by rakuri255** [comment]
Oh yes! Your right. Will fix it.
