### ISSUE TITLE
Google Colab without GPU

### ISSUE THREAD

**Issue by iacoposk8** [rakuri255/UltraSinger#143]
Hello, this isn’t really an issue but I’ve created this notebook on Google Colab.
https://colab.research.google.com/drive/1y1OyWH4QLPQtAoTXBpjqd2euHHsg0Y70#scrollTo=bhYisMBtiOZD
It works well, but I don’t understand why whisper runs it with the GPU while crepe doesn’t manage to and uses the CPU instead. If you want to copy this Google Colab into your project, feel free to do so ;)
Thanks

**Comment by rakuri255** [comment]
You have to give access rights

**Comment by iacoposk8** [comment]
how? with chmod? to which files? thank you

**Comment by rakuri255** [comment]
Wow! it works :D

You have to use tensorflow 2.15.0 in colab since they use Cuda 12.1 environment.
I still stick with 2.10.0 because they drop cuda for windows-nativ with version 2.11.0.

But seems crepe dislikes the 2.15.0 version.
You can try to install it with:
`!pip install tensorflow[and-cuda]==2.15.0`

**Comment by rakuri255** [comment]
so i also updated the tourch stuff to latest versions with cu121 so they can use Cuda 12.1.
And now crepe also works :)

**Comment by leoharantes** [comment]
Would you please share the Colab notebook file again?
I'm trying to use Colab myself and it is not working.

**Comment by LuisJimenezV** [comment]
Hello, I would like to try your code in Google Colab, because I had no success trying to install UltraSinger and the packages on my local computer. Is it possible for you to share it again?

**Comment by rakuri255** [comment]
I added the colab file and also added an "open in colab" link in top of the Readme.
Please try and give me an feedback if that works.

Yes, there are some torch install issue. Someone could update the versions 🤣 
But my first run works.
