### ISSUE TITLE
Hyphenation does not work. It cant download new languages

### ISSUE THREAD

**Issue by LanceAkaLance** [rakuri255/UltraSinger#147]
I tried multiple different songs and forcing them to use English, Italian and German as a language for transcription.
Every single time they had an error while hyphenating unless the language was set to German. 

Everything else works properly (except for torch throwing warnings that my kernel does not support NUMA, which seems to be a common issue for WSL users but apparantly can be ignored).

I am running UltraSinger on WSL Ubuntu. The Host-System is WIndows 11 Pro 23H2. My system language for Windows is German but the VM is in English. Its running Ubuntu 22.0.4 LTS. 

I have tried reinstalling the models and python modules and still got the same results.

These are my locale settings for Ubuntu
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=

**Comment by BanCrash** [comment]
Hyphenation is not working for me neither on Windows using english, while my computer language is spanish, so it seems that is not only related to WSL.

**Comment by rakuri255** [comment]
@LanceAkaLance can you post you log pls

**Comment by LanceAkaLance** [comment]
Ran it on my laptop using WSL, same result
```
(.venv) root@Laptop-G10:~/UltraSinger# python3.10 ./src/UltraSinger.py -i https://www.youtube.com/watch?v=9PNCVVrs7gk --
whisper small

[UltraSinger] *****************************
[UltraSinger] UltraSinger Version: 0.0.11-dev4
[UltraSinger] *****************************
[UltraSinger] Checking GPU support for tensorflow and pytorch.
2024-06-20 10:54:15.514527: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-06-20 10:54:15.514563: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-06-20 10:54:15.514657: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Laptop-G10): /proc/driver/nvidia/version does not exist
[UltraSinger] tensorflow - there are no cuda devices available -> Using cpu.
[UltraSinger] pytorch - there are no cuda devices available -> Using cpu.
[UltraSinger] full automatic mode
[youtube] Extracting URL: https://www.youtube.com/watch?v=9PNCVVrs7gk
[youtube] 9PNCVVrs7gk: Downloading webpage
[youtube] 9PNCVVrs7gk: Downloading ios player API JSON
[youtube] 9PNCVVrs7gk: Downloading tv embedded player API JSON
[youtube] 9PNCVVrs7gk: Downloading web embedded client config
[youtube] 9PNCVVrs7gk: Downloading player 84314bef
[youtube] 9PNCVVrs7gk: Downloading web embedded player API JSON
[UltraSinger] Searching song in musicbrainz
[UltraSinger] cant find title everything is a lot in will wood and the tapeworms  dr sunshine is dead official video
[UltraSinger] No match found
[UltraSinger] Creating output folder. -> /root/UltraSinger/output/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) (1)
[UltraSinger] Downloading Audio
[youtube] Extracting URL: https://www.youtube.com/watch?v=9PNCVVrs7gk
[youtube] 9PNCVVrs7gk: Downloading webpage
[youtube] 9PNCVVrs7gk: Downloading ios player API JSON
[youtube] 9PNCVVrs7gk: Downloading tv embedded player API JSON
[youtube] 9PNCVVrs7gk: Downloading web embedded client config
[youtube] 9PNCVVrs7gk: Downloading player 84314bef
[youtube] 9PNCVVrs7gk: Downloading web embedded player API JSON
[info] 9PNCVVrs7gk: Downloading 1 format(s): 251
[download] Destination: /root/UltraSinger/output/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) (1)/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video)
[download] 100% of    4.98MiB in 00:00:00 at 7.49MiB/s
[ExtractAudio] Destination: /root/UltraSinger/output/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) (1)/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video).mp3
Deleting original file /root/UltraSinger/output/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) (1)/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) (pass -k to keep)
[UltraSinger] Downloading Video
[youtube] Extracting URL: https://www.youtube.com/watch?v=9PNCVVrs7gk
[youtube] 9PNCVVrs7gk: Downloading webpage
[youtube] 9PNCVVrs7gk: Downloading ios player API JSON
[youtube] 9PNCVVrs7gk: Downloading tv embedded player API JSON
[youtube] 9PNCVVrs7gk: Downloading web embedded client config
[youtube] 9PNCVVrs7gk: Downloading player 84314bef
[youtube] 9PNCVVrs7gk: Downloading web embedded player API JSON
[info] 9PNCVVrs7gk: Downloading 1 format(s): 137
[download] Destination: /root/UltraSinger/output/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) (1)/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video).mp4
[download] 100% of  113.63MiB in 00:00:11 at 9.53MiB/s
[UltraSinger] Downloading thumbnail
[youtube] Extracting URL: https://www.youtube.com/watch?v=9PNCVVrs7gk
[youtube] 9PNCVVrs7gk: Downloading webpage
[youtube] 9PNCVVrs7gk: Downloading ios player API JSON
[youtube] 9PNCVVrs7gk: Downloading tv embedded player API JSON
[youtube] 9PNCVVrs7gk: Downloading web embedded client config
[youtube] 9PNCVVrs7gk: Downloading player 84314bef
[youtube] 9PNCVVrs7gk: Downloading web embedded player API JSON
[UltraSinger] Creating output folder. -> /root/UltraSinger/output/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) (1)/cache
[UltraSinger] Separating vocals from audio with demucs and cpu as worker.
Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in /root/UltraSinger/separated/htdemucs
Separating track /root/UltraSinger/output/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) (1)/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video).mp3
100%|██████████████████████████████████████████████| 327.59999999999997/327.59999999999997 [04:02<00:00,  1.35seconds/s]
[UltraSinger] Converting wav to mp3
[UltraSinger] Reduce noise from vocal audio with ffmpeg.
[UltraSinger] Converting audio for AI
[UltraSinger] Mute audio parts with no singing
[UltraSinger] Loading whisper with model small and cpu as worker
vocabulary.txt: 100%|████████████████████████████████████████████████████████████████| 460k/460k [00:00<00:00, 4.28MB/s]
config.json: 100%|█████████████████████████████████████████████████████████████████| 2.37k/2.37k [00:00<00:00, 10.1MB/s]
tokenizer.json: 100%|██████████████████████████████████████████████████████████████| 2.20M/2.20M [00:00<00:00, 6.88MB/s]
model.bin: 100%|█████████████████████████████████████████████████████████████████████| 484M/484M [00:49<00:00, 9.76MB/s]
No language specified, language will be first be detected for each audio file (increases inference time).
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.3.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.1+cu117. Bad things might happen unless you revert torch to 1.x.
[UltraSinger] Transcribing /root/UltraSinger/output/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) (1)/cache/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video)_mute.wav
Detected language: en (0.80) in first 30s of audio...
[UltraSinger] Hyphenate using language code: en
[UltraSinger] Error in hyphenation for language  en, maybe you want to disable it?
[UltraSinger] Removing silent parts from transcription data
[UltraSinger] Pitching with crepe and model full and cpu as worker
2024-06-20 11:01:11.515026: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
1007/1007 [==============================] - 279s 277ms/step
[UltraSinger] Creating midi notes from pitched data
[UltraSinger] Creating Ultrastar notes from midi data
[UltraSinger] BPM is 130.81
[UltraSinger] Creating /root/UltraSinger/output/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) (1)/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video).txt from transcription.
[UltraSinger] Calculating silence parts for linebreaks.
[UltraSinger] Creating /root/UltraSinger/output/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) (1)/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) [Karaoke].txt from transcription.
[UltraSinger] Calculating silence parts for linebreaks.
[UltraSinger] Parse ultrastar txt -> /root/UltraSinger/output/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) (1)/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video).txt
[UltraSinger] Calculating Ultrastar Points
[UltraSinger] Simple (octave high ignored) points
[UltraSinger] Total: 5709, notes: 5233, line bonus: 476, golden notes: 0
[UltraSinger] Accurate (octave high matches) points:
[UltraSinger] Total: 5695, notes: 5219, line bonus: 476, golden notes: 0
[UltraSinger] Creating Midi with pretty_midi
[UltraSinger] Creating midi instrument from Ultrastar txt
[UltraSinger] Creating midi file -> /root/UltraSinger/output/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video) (1)/Will Wood and the Tapeworms - Dr. Sunshine is Dead (Official Video).mid
```

**Comment by Aydonger** [comment]
Seems i have the same Problem.

I use the "run on windows".bat, german Windows 11 and convert german Songs. Work flawlessly. Then i tried english songs - and the Tool get stuck on "hypenation eng".

Any possible Solution?

**Comment by rakuri255** [comment]
Cnat find it on Windows.
I added a print for the exception. Maybe we can find it then.
Please update the your main to "0.0.12-dev1" and show the log again.

**Comment by LanceAkaLance** [comment]
Okay so I found a fix for hyphenation crashing instantly.
For some reason WSL does not come with any locales installed. Thats why my locales were "C.UTF-8".

This can be fixed by running `sudo apt update && sudo apt install language-pack-en`.

However I am now running into the same issue as @Aydonger 
The process never continues. There is no cpu activity coming from the hyphenation process. I also made sure that it does not run out of memory to rule that out as a cause.

Note that the version that is displayed in the log is inaccurate. I double checked the version in the Settings.py file and also removed and rebuilt the docker.

[UltraSingerLog.txt](https://github.com/user-attachments/files/16199748/UltraSingerLog.txt)

**Comment by Aydonger** [comment]
Grabbed the new Version ("0.0.12-dev1") and tried an english Song on my german Windows 11. Same result:

```
...
Detected language: en (0.76) in first 30s of audio...
[UltraSinger] Hyphenate using language code: en
```

The Tool stucks at this message, no CPU / GPU activity. When i try a german Song, even after this "crash" - it runs perfect.

I even tried to convert the english song with the "--language de Flag" and it worked. Well, the Result are bad, cause its an english song, but the tool convert it without any errors.

**Comment by BanCrash** [comment]
```
[UltraSinger] Error in hyphenation for language  en, maybe you want to disable it?
        ->504 Server Error: Gateway Timeout for url: https://cgit.freedesktop.org/libreoffice/dictionaries/plain//en/hyph_en.dic
```

I used the last main version and after a lot of time I got this error.

**Comment by rakuri255** [comment]
Maybe we should use this https://github.com/LibreOffice/dictionaries

**Comment by rakuri255** [comment]
ok [PyHyphen](https://github.com/dr-leo/PyHyphen) is just broken, outdated and unmanaged.
I forked it and try to fix this. 
Any help is welcome 😄 

- the CI is currently broken

https://github.com/rakuri255/PyHyphen

**Comment by BanCrash** [comment]
> ok [PyHyphen](https://github.com/dr-leo/PyHyphen) is just broken, outdated and unmanaged. I forked it and try to fix this. Any help is welcome 😄
> 
>     * the CI is currently broken
> 
> 
> https://github.com/rakuri255/PyHyphen

I don't know anything about this, but maybe https://github.com/Kozea/Pyphen could make the same trick?

**Comment by rakuri255** [comment]
@BanCrash I tried this library back then. I looked over it again and I don't think it can do syllables. The standard hypenation is not suitable for karaoke but more for text reading. It must be separated by syllables. 

Or can [Pyphen](https://github.com/Kozea/Pyphen) do that?

**Comment by LanceAkaLance** [comment]
Pyphen uses the same source for the dictionaries so hyphenation behaviour should be the same. Though also apparantly you can just change the download source in PyHyphen to achieve the same result.
(Which it appears you are already working on so good luck!)

**Comment by rakuri255** [comment]
@LanceAkaLance Yes, but as I understand it, the hyphenation is different. The hyphenation info is available in libreoffice but has to be used (syllables vs hyphens). 

I will probably try the package later. Because I'm not satisfied with the current solution anyway.

So i done my fix, CI builds again, the packages are ready. Need to register to PyPI and upload it. And than add it to UltraSinger. 
Sorry for the long wait 😭

**Comment by rakuri255** [comment]
Ok guys. Lets try UltraSinger 0.0.12-dev2 🗡️ 
You need to reinstall it!

Or manually uninstall PyHyphen and install PyHyphen-Reloaded..

**Comment by rakuri255** [comment]
For the discussion syllables vs Hyphen:

This is what we want:
```
h_en.syllables('beautiful')
['beau', 'ti', 'ful']
```

This is what the most "Hyphens" do:
```
h_en.pairs('beautiful'
[['beau', 'tiful'], ['beauti', 'ful']]

h_en.wrap('beautiful', 6)
['beau-', 'tiful']

h_en.wrap('beautiful', 7)
['beauti-', 'ful']
```

**Comment by Aydonger** [comment]
I delete my Ultrasinger Folder, dl the new Version from github. Run the "Install CUDA" script, then "run on windows" bat.

The following error occour:

```
[UltraSinger] Loading whisper with model large-v2 and cuda as worker
No language specified, language will be first be detected for each audio file (increases inference time).
Traceback (most recent call last):
  File "G:\ultrastarsinger\src\ultrasinger.py", line 992, in <module>
    main(sys.argv[1:])
  File "G:\ultrastarsinger\src\ultrasinger.py", line 884, in main
    run()
  File "G:\ultrastarsinger\src\ultrasinger.py", line 380, in run
    detected_language, transcribed_data = transcribe_audio()
  File "G:\ultrastarsinger\src\ultrasinger.py", line 510, in transcribe_audio
    transcribed_data, detected_language = transcribe_with_whisper(
  File "G:\ultrastarsinger\src\modules\Speech_Recognition\Whisper.py", line 35, in transcribe_with_whisper
    loaded_whisper_model = whisperx.load_model(
  File "G:\ultrastarsinger\.venv\lib\site-packages\whisperx\asr.py", line 347, in load_model
    vad_model = load_vad_model(torch.device(device), use_auth_token=None, **default_vad_options)
  File "G:\ultrastarsinger\.venv\lib\site-packages\whisperx\vad.py", line 47, in load_vad_model
    raise RuntimeError(
RuntimeError: Model has been downloaded but the SHA256 checksum does not not match. Please retry loading the model.
```

**Comment by rakuri255** [comment]
> I delete my Ultrasinger Folder, dl the new Version from github. Run the "Install CUDA" script, then "run on windows" bat.
> 
> The following error occour:
> 
> ```
> [UltraSinger] Loading whisper with model large-v2 and cuda as worker
> No language specified, language will be first be detected for each audio file (increases inference time).
> Traceback (most recent call last):
>   File "G:\ultrastarsinger\src\ultrasinger.py", line 992, in <module>
>     main(sys.argv[1:])
>   File "G:\ultrastarsinger\src\ultrasinger.py", line 884, in main
>     run()
>   File "G:\ultrastarsinger\src\ultrasinger.py", line 380, in run
>     detected_language, transcribed_data = transcribe_audio()
>   File "G:\ultrastarsinger\src\ultrasinger.py", line 510, in transcribe_audio
>     transcribed_data, detected_language = transcribe_with_whisper(
>   File "G:\ultrastarsinger\src\modules\Speech_Recognition\Whisper.py", line 35, in transcribe_with_whisper
>     loaded_whisper_model = whisperx.load_model(
>   File "G:\ultrastarsinger\.venv\lib\site-packages\whisperx\asr.py", line 347, in load_model
>     vad_model = load_vad_model(torch.device(device), use_auth_token=None, **default_vad_options)
>   File "G:\ultrastarsinger\.venv\lib\site-packages\whisperx\vad.py", line 47, in load_vad_model
>     raise RuntimeError(
> RuntimeError: Model has been downloaded but the SHA256 checksum does not not match. Please retry loading the model.
> ```

This error is related to whisper and is before the hyphen occures. Can you make a new issue?

**Comment by rakuri255** [comment]
@LanceAkaLance @BanCrash @Aydonger does it work now?

**Comment by Aydonger** [comment]
Yes, i can confirm, that (after the Hyphenation AND the WhisperX Error) the UltraSinger Script works again. Thanks!

**Comment by BanCrash** [comment]
Yes, me too.

**Comment by rakuri255** [comment]
Ok thanks for the help to find this issue!
