### ISSUE TITLE
Crepe stopping its work

### ISSUE THREAD

**Issue by BanCrash** [rakuri255/UltraSinger#15]
Hi, I tried to use but I can't get it to work. Always it got stucked here:

![imagen](https://github.com/rakuri255/UltraSinger/assets/11770760/47315d98-bcfd-4673-b769-1c1b4f8fa511)

And then just finish without any error or message.

I tried with different songs, whisper tiny, and --disable_separation True, but nothing of this work, it always end on the same point. I don't know if I'm doing something wrong, I'm using this:

UltraSinger.py -i "E:\song.mp3" -o E:\Test

Is there anything else I have to done?

**Comment by rakuri255** [comment]
Thanks for the input. There may be an error that is being swallowed. I'll check it out.

**Comment by rakuri255** [comment]
The project currently has a very high CPU load. Have you checked your CPU temperature?

**Comment by BanCrash** [comment]
![imagen](https://github.com/rakuri255/UltraSinger/assets/11770760/159b4508-b85c-4b13-aa11-bea1be414f2c)

I've tried with --crepe tiny but in the log it says it's model full, it's that correct? Two youtube's songs but both have ended before getting completed. 

With another song and --crepe tiny:
![imagen](https://github.com/rakuri255/UltraSinger/assets/11770760/08cf2404-8279-40f0-a204-5d304e4daff5)

Maybe the issue is because the temperature then.

With 20 seconds audio it ends as expected and generate all files.

All these tests were made with my previous downloaded version of this repository. Now I realized that there are a few more commits, so I made a quick test with the new version, but without any changes on the behaviour, it got ended after this:

![imagen](https://github.com/rakuri255/UltraSinger/assets/11770760/040bb834-9895-4a91-8959-5aed5b63e1a0)

**Comment by rakuri255** [comment]
Your CPU is burning 🔥. Its not healty 😃 .
Thanks for the input. I will look into the model issue.

**Comment by rakuri255** [comment]
Crepe model selection is now fixed. Sorry for that :)

**Comment by BanCrash** [comment]
> Your CPU is burning 🔥. Its not healty 😃 . Thanks for the input. I will look into the model issue.
> 
> There will be an GPU support in the future. But currently i dont know if you need a CUDA GPU for that.

Yep, not cool at all. 

My GPU has CUDA so it won't be a problem in my case.

I tried with last main, but now I've got another error:

![imagen](https://github.com/rakuri255/UltraSinger/assets/11770760/32731f2f-bbe0-4b27-8217-8187024ab270)

**Comment by rakuri255** [comment]
> > Your CPU is burning 🔥. Its not healty 😃 . Thanks for the input. I will look into the model issue.
> > There will be an GPU support in the future. But currently i dont know if you need a CUDA GPU for that.
> 
> Yep, not cool at all.
> 
> My GPU has CUDA so it won't be a problem in my case.
> 
> I tried with last main, but now I've got another error:
> 
> ![imagen](https://user-images.githubusercontent.com/11770760/239260405-32731f2f-bbe0-4b27-8217-8187024ab270.png)
> 
> I'm on Windows 10, if that is important.

Done. Thanks for the input!

**Comment by BanCrash** [comment]
If I execute it after starting the system, it will end. But after 1 or 2 hours, it will not end anymore, so it seems that it's the temperature issue.

Well, thank you for all your help!

**Comment by rakuri255** [comment]
I made an GPU support branch that hopfuly helps you.

The cpu intese vocal separation is now working with cuda.
Currently you need to lower Whisper model when your VRAM is only 8GB.
And crepe pitcher is still cpu limited.

**Comment by BanCrash** [comment]
Hi again, I've tried for some reason is not detecting my Nvidia 1060 6 GB, according to this page https://developer.nvidia.com/cuda-gpus my GPU has CUDA 6.1, and according to this one https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-22-09.html torch should be compatible with mine...

**Comment by rakuri255** [comment]
You also installed the new requirements from the .txt?

**Comment by BanCrash** [comment]
> You also installed the new requirements from the .txt?

Yes, I did, but now that you mention it, I got this error:

![imagen](https://github.com/rakuri255/UltraSinger/assets/11770760/b28d29a9-af32-4b8b-829f-5520bce7958c)

I don't know how to resolve it, to be honest.
