### ISSUE TITLE
UltraSinger / Python is broken

### ISSUE THREAD

**Issue by Aydonger** [rakuri255/UltraSinger#170]
I really dont know, what the Problem is - but there is some :)

1. Download the newest Verson of Ultrasinger. Overwrite the old Files. UltraSinger dont work (not starting).
2. Well, this might be a good opportunity, to start fresh. So i delete UltraSinger, delete also Python3.
3. DL Python 3.10.0 (on the Python Site, there are also 3.10.9 and 3.10.10 and so on). Installed it.
4. Start the UltraSinger GPU-Install-Script.
5. And here we are: error:

`Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      + meson setup C:\Users\xx\AppData\Local\Temp\pip-install-6id6vbs4\matplotlib_afeda52dd5dc4fb78aa35d850dadebd4 C:\Users\xx\AppData\Local\Temp\pip-install-6id6vbs4\matplotlib_afeda52dd5dc4fb78aa35d850dadebd4\.mesonpy-qfbxz_r0 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\xx\AppData\Local\Temp\pip-install-6id6vbs4\matplotlib_afeda52dd5dc4fb78aa35d850dadebd4\.mesonpy-qfbxz_r0\meson-python-native-file.ini
      The Meson build system
      Version: 1.5.1
      Source dir: C:\Users\xx\AppData\Local\Temp\pip-install-6id6vbs4\matplotlib_afeda52dd5dc4fb78aa35d850dadebd4
      Build dir: C:\Users\xx\AppData\Local\Temp\pip-install-6id6vbs4\matplotlib_afeda52dd5dc4fb78aa35d850dadebd4\.mesonpy-qfbxz_r0
      Build type: native build
      Program python3 found: YES
      Project name: matplotlib
      Project version: 3.9.1
      WARNING: Failed to activate VS environment: Could not parse vswhere.exe output`

      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
      Running `cl /?` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
      Running `cc --version` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
      Running `gcc --version` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
      Running `clang --version` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
      Running `clang-cl /?` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
      Running `pgcc --version` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"

      A full log can be found at C:\Users\xx\AppData\Local\Temp\pip-install-6id6vbs4\matplotlib_afeda52dd5dc4fb78aa35d850dadebd4\.mesonpy-qfbxz_r0\meson-logs\meson-log.txt
      [end of output]'

try another Python 3.10.x Version. No Luck. I tried also the Installation via Terminal. Again - no Luck.

And UltraSinger.py doesnt work either:

```
  File "PATH\src\UltraSinger.py", line 7, in <module>
    import Levenshtein
ModuleNotFoundError: No module named 'Levenshtein'
```

When i install the missing module via pip, another module is missing. And so on and so on...

the whole Application is broken and i dont know why :/

**Comment by HerrBockwurst** [comment]
Had the same problem. Installing C++ Dev Kid helped: https://learn.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=msvc-170

**Comment by Aydonger** [comment]
I delete everything from UltraSinger, the GIT and other Utils / Tools whatever. 
Installed GIT, added to the PATH (running on Windows). 
Then Installed the Visucal 2022 (Free Edition).
Installed the C++ Dev Enviroment
DL UltraSinger, start the CUDA GPU bat File.
This worked so far.

Then started a Conversation from a Music File ... and it worked!

**Comment by rakuri255** [comment]
I would like to know which py packages these two things need. Visual 2022 (Free Edition) and C++ Dev Enviroment. I have recently adjusted the requirements.txt for pip-compile. Maybe there is an unnecessary package in there now.

**Comment by Aydonger** [comment]
Sorry, cant understand how i contribute to this Question... i take the steps, suggesting from Mr. Bockwurst (the best Nickname in ages btw ^-^). 

"Had the same problem. Installing C++ Dev Kid helped: https://learn.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=msvc-170"

Then it runs. its possible, to collect some "log" Files or something, they show what is installed / downloaded? Cause i cant say, what Ultrasinger was dl 😭

**Comment by rakuri255** [comment]
Ok seems matplotlib version 3.9.1 causes the issue.
According to the release notes 3.9.2, the MSVC issue should be fixed.
https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.2.html

@Aydonger, @HerrBockwurst can you try and confirm this?
I just updated the requirements.txt

**Comment by janskod** [comment]
For me i just "changed matplotlib==3.9.1."to "matplotlib==3.9.1.**post1**" in the requirements.txt :
....
marshmallow==3.21.3
    # via dataclasses-json
matplotlib==3.9.1.**post1**
    # via
    #   -r requirements.in
    #   crepe
    #   music21
    #   pyannote-metrics

....

**Comment by rakuri255** [comment]
Was fixed here:
https://github.com/rakuri255/UltraSinger/commit/b057f2a78dfde6dc8e48a5f7d9eb10a096f628af
