### ISSUE TITLE
Fast spoken Text in mp3

### ISSUE THREAD

**Issue by McMuffin88** [rakuri255/UltraSinger#19]
i found an Problem with a fast singing Text in a song.

Caravan Palace - Lone Digger

No match in TXT  - after i tested in in Ultrastar - many Problems with Voice matching.

[Caravan Palace - Lone Digger.txt](https://github.com/rakuri255/UltraSinger/files/11537064/Caravan.Palace.-.Lone.Digger.txt)

Maybe a Bug?

**Comment by rakuri255** [comment]
Maybe will be fixed with #43

**Comment by McMuffin88** [comment]
Not complete but it is really better now.
If  not text come he has a funny feature inside ..
2420
: 2652 13 6 I 
: 2668 19 24 don't 
2687
: 2753 14 5 know 
2767
: 2923 4 11 what 
: 2928 2 12 to 
: 2932 3 11 do 
2935

and some start pitch are not so good - but better last time. Oh and a small problem with fast spoken words too... long line ^^ max Word per line will be better

![image](https://github.com/rakuri255/UltraSinger/assets/75749644/ff7acd47-d91e-49fb-8928-c937b0b85c19)
