### ISSUE TITLE
Not working with large-v3

### ISSUE THREAD

**Issue by BanCrash** [rakuri255/UltraSinger#199]
Hi, If I try to use large-v3 whisper model (which seems better than v2) it will always throw an error no matter what song I choose.

`[UltraSinger] Mute audio parts with no singing
Traceback (most recent call last):
  File "C:\Programas\UltraSinger\src\UltraSinger.py", line 708, in <module>
    main(sys.argv[1:])
  File "C:\Programas\UltraSinger\src\UltraSinger.py", line 579, in main
    run()
  File "C:\Programas\UltraSinger\src\UltraSinger.py", line 150, in run
    TranscribeAudio(process_data)
  File "C:\Programas\UltraSinger\src\UltraSinger.py", line 356, in TranscribeAudio
    transcription_result = transcribe_audio(process_data.process_data_paths.cache_folder_path,
  File "C:\Programas\UltraSinger\src\UltraSinger.py", line 475, in transcribe_audio
    transcription_config = f"{settings.transcriber}_{settings.whisper_model.value}_{settings.pytorch_device}_{whisper_align_model_string}_{settings.whisper_batch_size}_{settings.whisper_compute_type}_{settings.language}"
AttributeError: 'str' object has no attribute 'value'`

Arguments:

`UltraSinger.py -i <link> -o C:\Downloads\ --whisper large-v3 --disable_karaoke True`

**Comment by agwosdz** [comment]
Can you provide the whole output?

**Comment by agwosdz** [comment]
> Hi, If I try to use large-v3 whisper model (which seems better than v2) it will always throw an error no matter what song I choose.
> 
> `[UltraSinger] Mute audio parts with no singing Traceback (most recent call last): File "C:\Programas\UltraSinger\src\UltraSinger.py", line 708, in <module> main(sys.argv[1:]) File "C:\Programas\UltraSinger\src\UltraSinger.py", line 579, in main run() File "C:\Programas\UltraSinger\src\UltraSinger.py", line 150, in run TranscribeAudio(process_data) File "C:\Programas\UltraSinger\src\UltraSinger.py", line 356, in TranscribeAudio transcription_result = transcribe_audio(process_data.process_data_paths.cache_folder_path, File "C:\Programas\UltraSinger\src\UltraSinger.py", line 475, in transcribe_audio transcription_config = f"{settings.transcriber}_{settings.whisper_model.value}_{settings.pytorch_device}_{whisper_align_model_string}_{settings.whisper_batch_size}_{settings.whisper_compute_type}_{settings.language}" AttributeError: 'str' object has no attribute 'value'`
> 
> Arguments:
> 
> `UltraSinger.py -i <link> -o C:\Downloads\ --whisper large-v3 --disable_karaoke True`

Can you provide the entire output? Or the song link?

**Comment by agwosdz** [comment]
Pull request #200 will fix the issue, please take a look if you'd like to fix before commit. It's just adding one line, and changing one value

**Comment by agwosdz** [comment]
@rakuri255 Alternatively, Pull request #196 also addresses this. I have created a separate PR just in case you wanted to go for a quick fix. Might be in some others as well. One of the OQL was to check against the class to see if the model is a valid one and prompt the user if it was not in the class. Within that code, the setting is set as WhisperModel(arg).

**Comment by rakuri255** [comment]
Sorry for the bug. We need a unit test to make sure it doesn't break again. 

I tested v3 at release and it is partly better but mostly much worse than v2. There was also a discussion online somewhere where it was said that it is not usable for vocals. 

But I'm looking forward to your test results!
