### ISSUE TITLE
Errors after setup with install GPU (Windows)

### ISSUE THREAD

**Issue by daddelpaddel** [rakuri255/UltraSinger#202]
It´s really frustrating. I can´t get it running, even i did everything according instruction. Also have Python and GIT installed, ffmpeg and also set PATH in windows.  Installed CUDA drivers for Windows and choosed CUDA batch of course.

After successfull running of script, downloading and installing here and there (no error messages during installation) i start with run_on_windows.bat and get new window (.venv) E:\Ultrasinger\src>

When typing py Ultrasinger.py it takes a while and than i get following messages and do not know what to do

Traceback (most recent call last):
  File "E:\Ultrasinger\src\UltraSinger.py", line 21, in <module>
    from modules.Audio.youtube import (
  File "E:\Ultrasinger\src\modules\Audio\youtube.py", line 12, in <module>
    from modules.musicbrainz_client import search_musicbrainz
  File "E:\Ultrasinger\src\modules\musicbrainz_client.py", line 6, in <module>
    from src.Settings import Settings
ModuleNotFoundError: No module named 'src'

Anybody could help and solve my issues? I´m not an expert and also not familar with python etc.

Thanks

**Comment by agwosdz** [comment]
Hi, 

py is probably linked to your native python installation and not the venv. Try executing with **_python Ultrasinger.py_** :) Testing myself now

**Comment by agwosdz** [comment]
Are you by any chance using PowerShell as your default? If so, the .venv does not get properly activated. Try running the installer from "Command Prompt" (not terminal or powershell).

**Comment by daddelpaddel** [comment]
Finally i´ve got it running. With CUDA there was some problems, so I made clean install with CPU now. After running script and start Ultrasinger i´ve got same problems and messages as before. I´ve checked the musicbrainz_client.ply and changed 
from "src Settings import Setting"
to "from Settings import Settings"

Now Ultrasinger is running, doing all the steps and gerenarted several files and txt file. Did not checked final results in Ultrastar, but programm is running, this was my main goal to reach.

Okay, the names and title muscbrainz put out is nonsense, but if this is the "only" problem i can accept and rename my files manually.

I will give it a try to use command promt to run installer (for sure on another pc) and report in next days if this is better result

**Comment by agwosdz** [comment]
I was going to investigate. Thanks for catching that. I just put  PR #203 in for that.

**Comment by rakuri255** [comment]
Does this run now with the changes from #203?

We could provide an extra run script for activation in PS. #205 

For Musicbrainz. I think we should provide options for an manual search. #207

**Comment by agwosdz** [comment]
I am not sure if the installer is an issue after all. I had trouble in the past where the activation was not successful and the packages were installed in my main installation. Nonetheless, I created a small PR #209  to fix any possible issues, regardless of the shell. Rather than activating the venv (which we don't need to unless we are doing something more complicated), we can just run the python.exe within the venv to install into the venv

**Comment by rakuri255** [comment]
I think the issue was #203 
His log says -> ModuleNotFoundError: No module named 'src'
