### ISSUE TITLE
Inter-word spaces should be after the final syllable, not before the first syllable

### ISSUE THREAD

**Issue by bohning** [rakuri255/UltraSinger#21]

**Comment by bohning** [comment]
True, but shouldn’t we leave the times behind where we use text editors to edit song files? In any case, I believe it makes sense to harmonize all tools. USDX, US Manager, US Creator and USDB Syncer currently prefer/use spaces after the words, while YASS and UltraSinger prefer/use spaces before the word.

**Comment by rakuri255** [comment]
UltraSinger also adds the space at the end of the word

**Comment by rakuri255** [comment]
Made a unit test.. to be sure 😄 
b755f0bbbccb517c73ec25e28668fdf3f43a1d6c
