### ISSUE TITLE
Error in transcription

### ISSUE THREAD

**Issue by sergiohf** [rakuri255/UltraSinger#216]
I have installed in a docker container, without GPU. Run python3 UltraSinger.py --interactive, but the process is killed in transcription:

[UltraSinger] Loading whisper with model large-v2 and cpu as worker
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.3.3. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../.venv/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.3.0+cu121. Bad things might happen unless you revert torch to 1.x.
[UltraSinger] Transcribing /app/UltraSinger/src/output/music.wav
Killed

I dont know what happened, but in the output/cache folder is the wav files, but no transcription or any other ultrastar file.

The only other error was in the beginning:
2024-12-29 05:52:57.848369: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/app/UltraSinger/.venv/lib/python3.10/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")

**Comment by sergiohf** [comment]
It was the size of the model. I changed to medium and it worked.

**Comment by rakuri255** [comment]
@sergiohf can you give me your hardware specs? CPU, RAM, GPU & VRAM

**Comment by sergiohf** [comment]
> @sergiohf can you give me your hardware specs? CPU, RAM, GPU & VRAM

Its and old sony vaio, Intel® Core™ i7-2640M
cache 4 M,  3,50 GHz. Graphics intel 3000. 8gb of ram. Dont know about vram, but for sure it was vram problem, since with a medium model it worked

**Comment by rakuri255** [comment]
Your hardware is not good enough for UltraSinger.
Try Colab. Just click on the colab badge on the startpage.

**Comment by sergiohf** [comment]
Tks, its a personal "server", not expect great performance, but it worked well enough with the medium model, and i am interested in the .txt file generation and that was almos perfect. Great work by the way!
