### ISSUE TITLE
#LANGUAGE tag should be set

### ISSUE THREAD

**Issue by bohning** [rakuri255/UltraSinger#23]
The song’s language is detected anyways, so this information should be set in the song’s header as #LANGUAGE.

**Comment by rakuri255** [comment]
Nice. Didnt know there is a tag for that. 
Whats the types? Just `de` and `en` or do we need `de_DE` `de_AT` `en_GB` and so on

**Comment by rakuri255** [comment]
Its just a string

**Comment by rakuri255** [comment]
Write nativ language or english language? e.g. français or Frensh | Deutsch or German ?

**Comment by bohning** [comment]
The de facto standard is the English name, so German, English, French, Italian, Polish, etc.
