### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by kubalakowski** [rakuri255/UltraSinger#30]
Hi, tried to generate UltraStar files from polish song out of youtube

and encountered encoding issue with '\U0001f3b5' character.

> Traceback (most recent call last):
>   File "D:\Repozytoria\UltraSinger\UltraSinger.py", line 476, in <module>
>     main(sys.argv[1:])
>   File "D:\Repozytoria\UltraSinger\UltraSinger.py", line 429, in main
>     run()
>   File "D:\Repozytoria\UltraSinger\UltraSinger.py", line 263, in run
>     real_bpm, ultrastar_file_output = create_ultrastar_txt_from_automation(audio_separation_path,
>                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Repozytoria\UltraSinger\UltraSinger.py", line 329, in create_ultrastar_txt_from_automation
>     ultrastar_writer.create_ultrastar_txt_from_automation(transcribed_data, ultrastar_note_numbers,
>   File "D:\Repozytoria\UltraSinger\moduls\Ultrastar\ultrastar_writer.py", line 67, in create_ultrastar_txt_from_automation
>     f.write(transcribed_data[i].word)
>   File "C:\Python311\Lib\encodings\cp1250.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f3b5' in position 0: character maps to <undefined>

My guess would be that in ultrastar_writer.py in method create_ultrastar_txt_from_automation file should be opened with encoding='utf-8'.

That would also fix issue with encoding during playing Ultrastar, where some characters are not properly displayed

https://github.com/rakuri255/UltraSinger/blob/973e785e50ce35f8aadf03563e2af5b131870898/moduls/Ultrastar/ultrastar_writer.py#L30

Other issue is that directory and file names are lacking some of the characters that are removed because they are specific accent characters, instead they could be normalized (ąęół -> aeol).
(I wonder if there is any reason these accents need to be removed?)

https://github.com/rakuri255/UltraSinger/blob/973e785e50ce35f8aadf03563e2af5b131870898/UltraSinger.py#L355-L357

Love this project so far, I'm really surprised with the quality of generated songs especially that so far I'm only working with polish ones. Also perfect timing as I'm doing a karaoke next month and was missing a lot of songs no one ever mapped

**Comment by rakuri255** [comment]
Thanks for the info! I will into it.

**Comment by rakuri255** [comment]
> Other issue is that directory and file names are lacking some of the characters that are removed because they are specific accent characters, instead they could be normalized (ąęół -> aeol). (I wonder if there is any reason these accents need to be removed?)

The reason was that the file not contains special charecters that are not alowed in windows file names e.g. ?<>:*
I only tested English and German songs so far. Can you post the polish song, so that i can test?

**Comment by kubalakowski** [comment]
> > Other issue is that directory and file names are lacking some of the characters that are removed because they are specific accent characters, instead they could be normalized (ąęół -> aeol). (I wonder if there is any reason these accents need to be removed?)
> 
> The reason was that the file not contains special charecters that are not alowed in windows file names e.g. ?<>:* I only tested English and German songs so far. Can you post the polish song, so that i can test?

Sure, https://www.youtube.com/watch?v=3z-jNRAwSHk

**Comment by kubalakowski** [comment]
FYI: Managed to hotfix the issue by adding "unidecode" lib and normalizing accent characters before the regex

```
def download_from_youtube():
    title = get_youtube_title(settings.input_file_path)
    title = unidecode(title)
    basename_without_ext = re.sub('[^A-Za-z0-9. _-]+', '', title).strip()
```

https://stackoverflow.com/questions/517923/what-is-the-best-way-to-remove-accents-normalize-in-a-python-unicode-string

**Comment by bohning** [comment]
> (I wonder if there is any reason these accents need to be removed?)

I don’t think there is a reason and I recommend leaving them as is - Windows, Mac and Linux all support UTF8 filenames.

The syncer uses:
```
FILENAME_REPLACEMENTS = (('?:"', ""), ("<", "("), (">", ")"), ("/\\|*", "-"))


def sanitize_filename(fname: str) -> str:
    for old, new in FILENAME_REPLACEMENTS:
        for char in old:
            fname = fname.replace(char, new)
    if fname.endswith("."):
        fname = fname.rstrip(" .")  # Windows does not like trailing periods
    return fname
```

**Comment by rakuri255** [comment]
@kubalakowski thanks for the hot fix. But i think we should simply allow other chars :D
@bohning Thanks for the code! I just build it in.
