### ISSUE TITLE
Set Cover

### ISSUE THREAD

**Issue by rakuri255** [rakuri255/UltraSinger#38]
Get Cover from web or from YouTube video 

- [X] from YouTube video
- [x] from web
- [X] Convert to correct apect ratio

**Comment by rakuri255** [comment]
What is the correct aspect ratio? Or the best resolution?

**Comment by bohning** [comment]
correct aspect ratio is 1:1 (square), generally the larger the better (4K TV and USDX roulette has 1920x1920 px).

**Comment by bohning** [comment]
fanart.tv has high quality covers with (exactly) 1000x1000 px.

**Comment by rakuri255** [comment]
Youtube thumbnail crop to 1:1 ratio db717ecbea7b79fc7fa2f13cc3ddf4c03e4dc52c

**Comment by achimmihca** [comment]
MusicBrainz has a REST API to query album art and informations about songs.
They also define a unique identifier for artists, albums, and songs.

The MusicBrainz API is [free for non-commercial use](https://metabrainz.org/supporters/account-type).

**Comment by rakuri255** [comment]
@achimmihca i using musicbrainz  for additional infos. See #39.
Next step is to get the pictures from there.
But i think we should also use fanart.tv. At least for background.
