### ISSUE TITLE
Pitcher with gpu support

### ISSUE THREAD

**Issue by rakuri255** [rakuri255/UltraSinger#40]

**Comment by stripu** [comment]
Would integrating a pytorch version of crepe be better for gpu support? 
Ex, here: https://github.com/maxrmorrison/torchcrepe

**Comment by rakuri255** [comment]
Yes, i tested it, but had some issues. 
https://github.com/maxrmorrison/torchcrepe/issues/26

**Comment by stripu** [comment]
Ahh, I see, it outputs different data compared to original crepe.. 
Is there anything we could do to get better results with the normal crepe? Right now, pitching seems to be mostly one octave/half octave higher or lower compared to original song pitch

**Comment by rakuri255** [comment]
I'm already on the lookout there too.
What we need in any case is a short test file where the notes are very clear. 

Then the whole chain has to be checked, because every editing step could change the sound. 

* Vocal separation with Demucs 
* converting to mono wav
* different audio loadings (wavform vs librosa)
* ffmpeg filter
* silence remover
* crepe

**Comment by rakuri255** [comment]
Thanks to @BWagener for adding GPU Support with #89
