### ISSUE TITLE
generate music score for singing vocals

### ISSUE THREAD

**Issue by dutchsing009** [rakuri255/UltraSinger#52]
Can this tool be used to make or generate music score for singing vocals ? Im not so sure if  I'm understanding this tool correctly
so a clarification from you would be amazing. :)

**Comment by rakuri255** [comment]
Yes the plan is that the tool will create a sheet / music score later. But this is still in development / planning. See issue #7

**Comment by achimmihca** [comment]
Note that you can already take the generated MIDI file and export it to sheet music (e.g. PDF) using various tools.
For example, [MuseScore](musescore.org/) can export MIDI to sheet music.
