### ISSUE TITLE
Error when creating lyrics

### ISSUE THREAD

**Issue by prgrobots** [rakuri255/UltraSinger#57]
This was from a local mp3 on my windows machine using python 3.10.10.

It had split the audio 
![image](https://github.com/rakuri255/UltraSinger/assets/91106994/0149f4e2-6f04-4499-9444-d8a40be4aea8)
But seemed to stop when it was starting to create the lyrics.

[UltraSinger] Transcribing .\output\gd (6)\cache\gd_denoised.wav
Detected language: en (0.92) in first 30s of audio...
Downloading: "https://download.pytorch.org/torchaudio/models/wav2vec2_fairseq_base_ls960_asr_ls960.pth" to C:\Users\PC/.cache\torch\hub\checkpoints\wav2vec2_fairseq_base_ls960_asr_ls960.pth
100%|█████████████████████████████████████████████████████████████████████████████████████| 360M/360M [08:42<00:00, 723kB/s] 
File "C:\Users\PC\Music\test\UltraSinger\UltraSinger.py", line 803, in <module>
    main(sys.argv[1:])
  File "C:\Users\PC\Music\test\UltraSinger\UltraSinger.py", line 746, in main
    run()
  File "C:\Users\PC\Music\test\UltraSinger\UltraSinger.py", line 348, in run
    remove_unecessary_punctuations(transcribed_data)
  File "C:\Users\PC\Music\test\UltraSinger\UltraSinger.py", line 256, in remove_unecessary_punctuations
    transcribed_data[i].word = transcribed_data[i].word.translate(
TypeError: list indices must be integers or slices, not tuple

**Comment by rakuri255** [comment]
Thanks! Can you give me the Song name or Youtube link so that i can reproduce it?

**Comment by rakuri255** [comment]
Should now be fixed with fbd18ee7afbf9181bcc2f1ee9438c05c179e655b
