### ISSUE TITLE
Whisper error when detected language is "ro" (Romanian) 

### ISSUE THREAD

**Issue by stripu** [rakuri255/UltraSinger#61]
So when trying to use this for a romanian song I  get the following error, on the transcribing phase:

[UltraSinger] Transcribing F:\UltraSinger\output\Laura Stoica - Mai frumoasa (2)\cache\Laura Stoica - Mai frumoasa_denoised.wav
Detected language: ro (0.98) in first 30s of audio...
There is no default alignment model set for this language (ro).                Please find a wav2vec2.0 model finetuned on this language in https://huggingface.co/models, then pass the model name in --align_model [MODEL_NAME]
Traceback (most recent call last):
  File "F:\UltraSinger\UltraSinger.py", line 780, in <module>
    main(sys.argv[1:])
  File "F:\UltraSinger\UltraSinger.py", line 709, in main
    run()
  File "F:\UltraSinger\UltraSinger.py", line 308, in run
    language, transcribed_data = transcribe_audio()
  File "F:\UltraSinger\UltraSinger.py", line 402, in transcribe_audio
    transcribed_data, language = transcribe_with_whisper(
  File "F:\UltraSinger\src\modules\Speech_Recognition\Whisper.py", line 37, in transcribe_with_whisper
    model_a, metadata = whisperx.load_align_model(
  File "F:\UltraSinger\.venv\lib\site-packages\whisperx\alignment.py", line 64, in load_align_model
    raise ValueError(f"No default align-model for language: {language_code}")
ValueError: No default align-model for language: ro

I'm new to python and wav2vec, but from what i could manage to understand is that probably it can't manage to find the model for romanian.
After checking out huggingface, i could find some wav2vec2 models, like this one: https://huggingface.co/gigant/romanian-wav2vec2
but I have no idea how to set it as the current model for transcribing.

Can you please advise? 

Thanks for your work on this, it's awesome. Tested it on some english songs and it works wonders, with a accuracy of around 95% in lyrics transcribing (or more!) and the pitching seems spot on.

**Comment by rakuri255** [comment]
Thanks for the report and feedback!
It is currently not possible to add other whisper models to UltraSinger. 

I will look at i when i have time :)

**Comment by rakuri255** [comment]
Ok it was easier then i though :)
See readme how to add other language models

**Comment by rakuri255** [comment]
@stripu please help others and post the model that works good for you here: https://github.com/rakuri255/UltraSinger/discussions/63
