### ISSUE TITLE
Store music database IDs in txt file

### ISSUE THREAD

**Issue by achimmihca** [rakuri255/UltraSinger#70]
I found that [you are using MusicBrainz](https://github.com/rakuri255/UltraSinger/blob/main/src/modules/musicbrainz_client.py) database to get song information such as year, genre, artist, etc.

I think it makes sense to add the [MBID](https://musicbrainz.org/doc/MusicBrainz_Identifier) to the txt file for future reference.
For example, other tools or games may use it to provide a link with further info to MusicBrainz.com or to fetch the album art if not present yet.

Suggestions for the UltraStar txt header fields: `MBID_RECORD`, `MBID_ARTIST`, `MBID_RELEASE_GROUP`, etc.

**Comment by bohning** [comment]
But isn’t `artist = artists['artist-list'][0]['name']` simply taking the first artist of the search result, no matter if it is correct or not? It might be highly likely the very first entry, but in case it’s not a perfect match, it might also be some other entry of the search results, right? So it is dangerous to add MBID to a song based on best-guessing, isn’t it? (same for release group).

**Comment by rakuri255** [comment]
@bohning yeah thats true. I thin it would be enough if we implement a better checker if it is the artist & title.
I also planing to trigger the search manually. See #75
That would help with odd youtube names.

**Comment by achimmihca** [comment]
Good point.

If the user specifies a MBID manually, then it might make sense to save this for future reference.

In contrast, an automatically chosen MBID might cause issues.

**Comment by rakuri255** [comment]
@achimmihca Good point by just providing the MBID.

**Comment by rakuri255** [comment]
Will be added, when specification is done in [UltraStar-Deluxe/format](https://github.com/UltraStar-Deluxe/format/issues/19)

**Comment by rakuri255** [comment]
The result from https://github.com/UltraStar-Deluxe/format/issues/19 is, that it will be not added to the format.
So i close this as "wont do"
