### ISSUE TITLE
Remove `src.` from module import: ModuleNotFoundError: No module named 'src' (on Windows)

### ISSUE THREAD

**Issue by achimmihca** [rakuri255/UltraSinger#71]
I installed dependencies successfully and changed to the virtual environment.

But when I try to run the main file, then I get

```
Traceback (most recent call last):
  File "F:\Dev\Projects\GitHub\UltraSinger\src\UltraSinger.py", line 13, in <module>
    from src.modules import os_helper
ModuleNotFoundError: No module named 'src'
```

Tried to start the code from `F:\Dev\Projects\GitHub\UltraSinger\src` and from `F:\Dev\Projects\GitHub\UltraSinger` but both fail.

Looking at the code, I found that modules are referenced for example with `from src.modules.Audio.denoise`.

Obviously this works for you, which I think is weird. VSCode also does not complain.
But on Windows I have to remove the `src.` part from the import to make it work.

It's been a while since I did stuff with Python, but in [Dedo Mouse](https://github.com/achimmihca/DedoMouse) I also referenced modules relative to the root code file.

Here, the root code file is UltraSinger.py, which is already in the src folder. Thus, other modules and files need to be referenced from this folder such that `from src.modules.Audio.denoise` should be written as `from from modules.Audio.denoise`.

I tested this and when I replace all `from src.` with `from `, then it works fine.

Please, check if it still works for you when you remove `src.` from the imports.

**Comment by rakuri255** [comment]
Ok thanks for the info, will look into it.
I use [PyCharm](https://www.jetbrains.com/de-de/pycharm/) and it works with `venv` and `conda`.

**Comment by stripu** [comment]
I had this error, but i copied all the files out of the src folder into the root and all runs well

**Comment by 64nd3r0lf** [comment]
I had this error and fixed it by adding `sys.path.append(“C:\\path\\to\\dir”)` to the `UltraSinger.py`

**Comment by achimmihca** [comment]
The suggested issues are workarounds to the issue.

The proper solution would be to fix the imports by removing the 'src.' part.

I can create a PR this weekend

**Comment by rakuri255** [comment]
This should do it: e74c35ee965b5f19b70b579490f5841f6ca29d35

**Comment by rakuri255** [comment]
According to discord chat it works now

**Comment by rakuri255** [comment]
Now tests are broken 🙈

**Comment by achimmihca** [comment]
Question is where pytest is looking for modules

- some suggest to configure `pyproject.toml`
    - https://stackoverflow.com/questions/10253826/path-issue-with-pytest-importerror-no-module-named-yadayadayada
- some suggest to add `__init__.py` to mark module directories

I suggest to look at a repo on GitHub that can be used as template.

**Comment by rakuri255** [comment]
@achimmihca thanks. `pyproject.toml` does the trick for the tests.
`__init__.py` is already in the `CI` branch
