### ISSUE TITLE
Whisper compute_type float16 does not work on older GPUs

### ISSUE THREAD

**Issue by rakuri255** [rakuri255/UltraSinger#81]
Older GPUss like GTX1080 cant use float16, so it needs int8. 
How to check this in code?
https://github.com/guillaumekln/faster-whisper/issues/42

**Comment by BanCrash** [comment]
> Older GPUss like GTX1080 cant use float16, so it needs int8. How to check this in code? [guillaumekln/faster-whisper#42](https://github.com/guillaumekln/faster-whisper/issues/42)

I'm not good with python but wouldn't be enough with a try - catch? Assuming that not having float16 would throw an error, which I don't know if that's the case.

```
try:
   compute_type = "float16"
   call_function(compute_type)
except:
   compute_type = "int8"
   call_function(compute_type)

```

**Comment by rakuri255** [comment]
Thanks to @BWagener for PR #89. Now you can chance the compute_type for whisper. See Readme.
```
    --whisper_batch_size    Reduce if low on GPU mem >> ((default) is 16)
    --whisper_compute_type  Change to "int8" if low on GPU mem (may reduce accuracy) >> ((default) is "float16" for cuda devices, "int8" for cpu)
```

**Comment by thepenguinthatwants** [comment]
Using docker-compose and compose-gpu.yml

edited the line to be


    whisper_compute_type = int8   # change to "int8" if low on GPU mem (may reduce accuracy)
NameError: name 'int8' is not defined. Did you mean: 'int'?
