### ISSUE TITLE
Create an optional instrumental track

### ISSUE THREAD

**Issue by Baklap4** [rakuri255/UltraSinger#86]
Not persé an issue to create txt files from song files.. but i see loads of "complete" songs do not come with an instrumental version. This is sad as many people would like to sing without backing vocals (if they're brave enough)

Would it be possible to include [spleeter](https://github.com/deezer/spleeter) to create an instrumental version of the song preferably through an option checkmark: "Create instrumental version"

**Comment by rakuri255** [comment]
@Baklap4  what do you mean? UltraSinger already creates an `* [Karaoke].txt` with instrumentals. UltraSinger uses DemucsV4 instead of spleeter, because it has slightly less noise.

**Comment by Baklap4** [comment]
Oh wow my bad i completely missed this hahah. Closing the issue 👍
