### ISSUE TITLE
Upgrade to official format Version

### ISSUE THREAD

**Issue by rakuri255** [rakuri255/UltraSinger#93]
# Add missing tags:
- [x] Version Header 1.0.0
- [x] Make Version switchable
# Remove special tags:
- [x] Fixer

See: [[Spec] Define Versions 0.1.0 / 0.2.0 / 0.3.0 / 1.0.0 / 1.1.0](https://github.com/UltraStar-Deluxe/format/issues/31)

**Comment by Baklap4** [comment]
I'd wait until it's finalized and we got a consensus, but nice to see that issues are already opening up to support the spec! 🎉
